#! /usr/bin/env python3

# Version 1.0 ~ Sean, Jakob, Spartak
# Reads the File just like the Task specifies it

def main():
    with open("data.bin", 'rb') as file:
        partOne = int.from_bytes(file.read(2), byteorder = "big", signed=False) # read first 2 bytes in big endian order; unsigned, so signed=False

        partTwo = int.from_bytes(file.read(1), byteorder = "little") + int.from_bytes(file.read(1), byteorder = "little") # read 2 byte in little endian order

        partThree = int.from_bytes(file.read(8), byteorder = "big") # read 8 bytes in big endian order

        partFour = int(file.read().decode("utf-8"), base=16) # read the rest, decode to utf-8 and convert to an int

        print(sum([partOne, partTwo, partThree, partFour])) # print sum of all values, last one is convert to an int

if __name__ == "__main__":
    main()